galaxy_info:
  author: Imperva Global Solutions Architecture team
  description: Example Role for managing Imperva agent on the RHEL 7 platform
  company: Imperva
  license: Imperva-Community Developer License
  min_ansible_version: 2.9
  platforms:
  - name: EL
    versions:
    - 7

  galaxy_tags:
    - imperva
    - security
    - database
dependencies: []
